from __future__ import annotations


class ProCoreMainSignalsMixin:
    def _connect_application_signals(self) -> None:
        self.splash.finished.connect(self.show_login)
        self.login_window.login_requested.connect(self.handle_login)
        self.login_window.password_reset_requested.connect(self.handle_password_reset_request)
        self.login_window.backend_reconnect_requested.connect(self.handle_login_backend_reconnect)
        self.password_window.password_change_requested.connect(self.handle_password_change)
        self.dashboard_window.logout_requested.connect(self.handle_logout)
        self.dashboard_window.exit_requested.connect(self.qt_app.quit)
        self.dashboard_window.module_selected.connect(self.load_module)
        self.dashboard_window.refresh_requested.connect(self.refresh_active_module)
        self.dashboard_window.customer_create_requested.connect(self.handle_customer_create)
        self.dashboard_window.customer_update_requested.connect(self.handle_customer_update)
        self.dashboard_window.customer_delete_requested.connect(self.handle_customer_delete)
        self.dashboard_window.customer_document_upload_requested.connect(
            self.handle_customer_document_upload
        )
        self.dashboard_window.equipment_create_requested.connect(self.handle_equipment_create)
        self.dashboard_window.equipment_update_requested.connect(self.handle_equipment_update)
        self.dashboard_window.equipment_delete_requested.connect(self.handle_equipment_delete)
        self.dashboard_window.equipment_board_create_requested.connect(
            self.handle_equipment_board_create
        )
        self.dashboard_window.equipment_board_update_requested.connect(
            self.handle_equipment_board_update
        )
        self.dashboard_window.equipment_board_delete_requested.connect(
            self.handle_equipment_board_delete
        )
        self.dashboard_window.equipment_component_create_requested.connect(
            self.handle_equipment_component_create
        )
        self.dashboard_window.equipment_component_update_requested.connect(
            self.handle_equipment_component_update
        )
        self.dashboard_window.equipment_component_delete_requested.connect(
            self.handle_equipment_component_delete
        )
        self.dashboard_window.equipment_defect_cases_requested.connect(
            self.handle_equipment_defect_cases
        )
        self.dashboard_window.equipment_import_requested.connect(self.handle_equipment_import)
        self.dashboard_window.equipment_export_requested.connect(self.handle_equipment_export)
        self.dashboard_window.inventory_create_requested.connect(self.handle_inventory_create)
        self.dashboard_window.inventory_update_requested.connect(self.handle_inventory_update)
        self.dashboard_window.inventory_delete_requested.connect(self.handle_inventory_delete)
        self.dashboard_window.inventory_document_download_requested.connect(
            self.handle_inventory_document_download
        )
        self.dashboard_window.sector_create_requested.connect(self.handle_sector_create)
        self.dashboard_window.sector_update_requested.connect(self.handle_sector_update)
        self.dashboard_window.sector_delete_requested.connect(self.handle_sector_delete)
        self.dashboard_window.service_order_create_requested.connect(
            self.handle_service_order_create
        )
        self.dashboard_window.service_order_update_requested.connect(
            self.handle_service_order_update
        )
        self.dashboard_window.service_order_delete_requested.connect(
            self.handle_service_order_delete
        )
        self.dashboard_window.service_order_diagnosis_requested.connect(
            self.handle_service_order_diagnosis
        )
        self.dashboard_window.service_order_budget_item_requested.connect(
            self.handle_service_order_budget_item
        )
        self.dashboard_window.service_order_submit_quote_requested.connect(
            self.handle_service_order_submit_quote
        )
        self.dashboard_window.service_order_approve_requested.connect(
            self.handle_service_order_approve
        )
        self.dashboard_window.service_order_reject_requested.connect(
            self.handle_service_order_reject
        )
        self.dashboard_window.service_order_start_requested.connect(self.handle_service_order_start)
        self.dashboard_window.service_order_complete_requested.connect(
            self.handle_service_order_complete
        )
        self.dashboard_window.service_order_document_upload_requested.connect(
            self.handle_service_order_document_upload
        )
        self.dashboard_window.user_create_requested.connect(self.handle_user_create)
        self.dashboard_window.user_update_requested.connect(self.handle_user_update)
        self.dashboard_window.user_delete_requested.connect(self.handle_user_delete)
        self.dashboard_window.user_password_reset_requested.connect(self.handle_user_password_reset)
        self.dashboard_window.user_resource_access_update_requested.connect(
            self.handle_user_resource_access_update
        )
        self.dashboard_window.password_reset_resolve_requested.connect(
            self.handle_password_reset_resolve
        )
        self.dashboard_window.password_reset_cancel_requested.connect(
            self.handle_password_reset_cancel
        )
        self.dashboard_window.settings_update_requested.connect(self.handle_settings_update)
        self.dashboard_window.ui_scale_changed.connect(self.handle_ui_scale_changed)
        self.dashboard_window.backup_run_requested.connect(self.handle_backup_run)
        self.dashboard_window.backend_restart_requested.connect(self.handle_backend_restart)
        self.dashboard_window.customer_portal_open_requested.connect(
            self.handle_open_customer_portal
        )
        self.dashboard_window.audit_delete_requested.connect(self.handle_audit_log_delete)
