from __future__ import annotations

from PySide6.QtCore import QTimer
from PySide6.QtWidgets import QFrame, QHBoxLayout, QLabel, QPushButton, QVBoxLayout


def build_dashboard_footer(self, scroll_area) -> None:
    self.session_footer = QFrame()
    self.session_footer.setObjectName("sessionFooter")
    session_footer_layout = QHBoxLayout(self.session_footer)
    session_footer_layout.setContentsMargins(10, 4, 10, 4)
    session_footer_layout.setSpacing(8)
    self.session_footer_label = QLabel("Sessao: -")
    self.session_footer_label.setObjectName("sessionFooterText")
    self.backend_status_dot = QLabel("●")
    self.backend_status_dot.setObjectName("footerStatusDot")
    self.backend_status_dot.setProperty("level", "error")
    self.backend_status_text = QLabel("Backend: desconectado")
    self.backend_status_text.setObjectName("sessionFooterText")
    self.internal_server_status_dot = QLabel("●")
    self.internal_server_status_dot.setObjectName("footerStatusDot")
    self.internal_server_status_dot.setProperty("level", "warning")
    self.internal_server_status_text = QLabel("Servidor interno: pendente")
    self.internal_server_status_text.setObjectName("sessionFooterText")
    self.footer_message_label = QLabel("")
    self.footer_message_label.setObjectName("footerMessage")
    self.footer_message_label.setProperty("level", "info")
    self.session_module_label = QLabel("Painel Principal")
    self.session_module_label.setObjectName("sessionFooterModule")
    session_footer_layout.addWidget(self.session_footer_label)
    session_footer_layout.addStretch()
    session_footer_layout.addWidget(self.footer_message_label, 1)
    session_footer_layout.addWidget(self.backend_status_dot)
    session_footer_layout.addWidget(self.backend_status_text)
    session_footer_layout.addWidget(self.internal_server_status_dot)
    session_footer_layout.addWidget(self.internal_server_status_text)
    session_footer_layout.addWidget(self.session_module_label)

    self.session_timer = QTimer(self)
    self.session_timer.setInterval(1000)
    self.session_timer.timeout.connect(self._refresh_session_footer)
    self.session_timer.start()

    main_area = QFrame()
    main_area.setObjectName("mainArea")
    main_area_layout = QHBoxLayout(main_area)
    main_area_layout.setContentsMargins(0, 0, 0, 0)
    main_area_layout.setSpacing(0)
    main_area_layout.addWidget(self.sidebar)
    main_area_layout.addWidget(scroll_area, 1)

    self.command_bar = QFrame()
    self.command_bar.setObjectName("topCommandBar")
    command_layout = QHBoxLayout(self.command_bar)
    command_layout.setContentsMargins(12, 6, 12, 6)
    command_layout.setSpacing(8)
    self.command_context_label = QLabel("Painel Principal")
    self.command_context_label.setObjectName("sessionFooterModule")
    command_layout.addWidget(self.command_context_label)
    self.command_stage_label = QLabel("Etapa 1")
    self.command_stage_label.setObjectName("moduleStageBadge")
    self.command_hint_label = QLabel("")
    self.command_hint_label.setObjectName("moduleActionHint")
    self.command_hint_label.setWordWrap(True)
    command_layout.addWidget(self.command_stage_label)
    command_layout.addWidget(self.command_hint_label, 1)
    command_layout.addStretch()

    self.command_refresh_button = QPushButton("Atualizar", self)
    self.command_refresh_button.setObjectName("secondaryButton")
    self.command_refresh_button.clicked.connect(self.refresh_requested.emit)
    self.command_editor_button = QPushButton("Editor", self)
    self.command_editor_button.setObjectName("secondaryButton")
    self.command_editor_button.setEnabled(False)
    self.command_editor_button.clicked.connect(self._open_record_editor)
    self.command_clear_selection_button = QPushButton("Limpar selecao", self)
    self.command_clear_selection_button.setObjectName("secondaryButton")
    self.command_clear_selection_button.setEnabled(False)
    self.command_clear_selection_button.clicked.connect(self._clear_current_selection)
    command_layout.addWidget(self.command_refresh_button)
    command_layout.addWidget(self.command_editor_button)
    command_layout.addWidget(self.command_clear_selection_button)

    layout = QVBoxLayout(self)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(0)
    layout.addWidget(self.command_bar)
    layout.addWidget(main_area, 1)
    layout.addWidget(self.session_footer)
