from __future__ import annotations

RADIUS_SM = 4
RADIUS_MD = 6
RADIUS_LG = 8

SPACE_1 = 4
SPACE_2 = 8
SPACE_3 = 12
SPACE_4 = 16

FOOTER_MESSAGE_TIMEOUT_MS = 6500
EQUIPMENT_SCROLL_MIN_HEIGHT = 820
EDITOR_DEFAULT_MAX_HEIGHT = 760
EDITOR_SERVICE_ORDER_MAX_HEIGHT = 860
